name: Build site at repo root

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-root:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml markdown

      - name: Generate site into repo root
        run: |
          python scripts/build_site.py --out .

      - name: Commit and push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update generated site at repo root [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
